name: Meson CI

on:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**/meson.build"
  pull_request:
    paths:
      - "**.cpp"
      - "**.h"
      - "**/meson.build"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - name: Configure project
        run: nix develop -c -- meson setup builddir/
      - name: Run Tests
        run: nix develop -c -- meson test -C builddir/ -v
      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
